name: Dead Links
description: Run Dead Links Tests
runs:
  using: "composite"
  steps: 
    - run: npm ci
      shell: bash
    - run: npm run doc-prepare
      shell: bash
    - run: $(npm bin)/kuzdoc iterate-repos:install --repos_path doc/framework/.repos/
      shell: bash
    - run: $(npm bin)/kuzdoc framework:link -d /sdk/dart/2/ -v 2
      shell: bash
    - run: sudo gem install typhoeus
      shell: bash
    - run: cd doc/framework/ && HYDRA_MAX_CONCURRENCY=20 ruby .ci/dead-links.rb -p src/sdk/dart/2/
      shell: bash
