
name: Release workflow

on: [release]

jobs:
  deploy:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - run: pub publish
